version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: BuildDocker-evtpay-payment-system
      env:
        variables:
        variables:
          APP_DIR: evtpay-payment-system
          IMAGE_REPO_NAME: evtpay-payment-system
      ignore-failure: true

    - identifier: BuildDocker-evtpay-admin-api
      env:
        variables:
        variables:
          APP_DIR: evtpay-admin-api
          IMAGE_REPO_NAME: evtpay-admin-api
      ignore-failure: true

    - identifier: BuildDocker-evtpay-api-gateway
      env:
        variables:
        variables:
          APP_DIR: evtpay-api-gateway
          IMAGE_REPO_NAME: evtpay-api-gateway
      ignore-failure: true

    - identifier: BuildDocker-evtpay-auth-provider
      env:
        variables:
        variables:
          APP_DIR: evtpay-auth-provider
          IMAGE_REPO_NAME: evtpay-auth-provider
      ignore-failure: true

    - identifier: BuildDocker-evtpay-config-server
      env:
        variables:
        variables:
          APP_DIR: evtpay-config-server
          IMAGE_REPO_NAME: evtpay-config-server
      ignore-failure: true

    - identifier: BuildDocker-evtpay-crm
      env:
        variables:
        variables:
          APP_DIR: evtpay-crm
          IMAGE_REPO_NAME: evtpay-crm
      ignore-failure: true

    - identifier: BuildDocker-evtpay-payment-system
      env:
        variables:
        variables:
          APP_DIR: evtpay-payment-system
          IMAGE_REPO_NAME: evtpay-payment-system
      ignore-failure: true

    - identifier: BuildDocker-evtpay-wallet
      env:
        variables:
        variables:
          APP_DIR: evtpay-wallet
          IMAGE_REPO_NAME: evtpay-wallet
      ignore-failure: true
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - cd $APP_DIR
      - echo "Building Ping Application"
      - echo Build started on `date`
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG